const viewport=document.getElementById('viewport');const tree=document.getElementById('tree');const props=document.getElementById('properties');const status=document.querySelector('.status');
let scene,camera,renderer,raycaster,mouse,selected=null,running=false;const objects=[];
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x0d1014);camera=new THREE.PerspectiveCamera(60,1,.1,1000);camera.position.set(8,7,10);camera.lookAt(0,0,0);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));viewport.appendChild(renderer.domElement);raycaster=new THREE.Raycaster();mouse=new THREE.Vector2();scene.add(new THREE.HemisphereLight(0xffffff,0x334455,2));scene.add(new THREE.DirectionalLight(0xffffff,1));scene.add(new THREE.GridHelper(30,30,0x555b66,0x292e36));addPart('Baseplate',0,-.5,0,14,1,14,0x3b7d3b);addPart('Part',0,.5,0,2,1,2,0x4da3ff);window.addEventListener('resize',resize);renderer.domElement.addEventListener('pointerdown',pick);resize();animate();renderTree()}
function addPart(name,x,y,z,sx=2,sy=1,sz=2,color=0x4da3ff){const g=new THREE.BoxGeometry(sx,sy,sz);const m=new THREE.MeshStandardMaterial({color,roughness:.75});const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.userData={name,position:o.position,size:[sx,sy,sz],color:'#'+color.toString(16).padStart(6,'0')};scene.add(o);objects.push(o);return o}
function renderTree(){tree.innerHTML='<div class="node">▾ Workspace</div><div class="node child">▾ World</div>';objects.forEach(o=>{const d=document.createElement('div');d.className='node child'+(o===selected?' selected':'');d.textContent='▣ '+o.userData.name;d.onclick=()=>select(o);tree.appendChild(d)})}
function select(o){selected=o;objects.forEach(x=>x.material.emissive.setHex(0));if(o)o.material.emissive.setHex(0x224466);showProps();renderTree();status.textContent=o?'Selected: '+o.userData.name:'Ready'}
function showProps(){if(!selected){props.innerHTML='<p class="muted">Select an object.</p>';return}const p=selected.position,s=selected.scale;props.innerHTML=`<div class="prop"><label>Name</label><input id="name" value="${selected.userData.name}"></div><div class="prop"><label>Position X</label><input id="px" type="number" step="0.1" value="${p.x}"></div><div class="prop"><label>Position Y</label><input id="py" type="number" step="0.1" value="${p.y}"></div><div class="prop"><label>Position Z</label><input id="pz" type="number" step="0.1" value="${p.z}"></div><div class="prop"><label>Scale</label><input id="scale" type="number" min="0.1" step="0.1" value="${s.x}"></div><div class="prop"><label>Color</label><input id="color" type="color" value="${selected.userData.color}"></div>`;['name','px','py','pz','scale','color'].forEach(id=>document.getElementById(id).addEventListener('change',()=>{if(id==='name')selected.userData.name=document.getElementById(id).value;else if(id==='color'){selected.userData.color=document.getElementById(id).value;selected.material.color.set(selected.userData.color)}else if(id==='scale'){const v=Math.max(.1,Number(document.getElementById(id).value));selected.scale.set(v,v,v)}else selected.position[id[1].toLowerCase()]=Number(document.getElementById(id).value);renderTree()}))}
function pick(e){const r=renderer.domElement.getBoundingClientRect();mouse.x=((e.clientX-r.left)/r.width)*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(mouse,camera);const hits=raycaster.intersectObjects(objects);select(hits.length?hits[0].object:null)}
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)}
function animate(){requestAnimationFrame(animate);if(running)objects.filter(o=>o.userData.name!=='Baseplate').forEach(o=>o.rotation.y+=.01);renderer.render(scene,camera)}
function projectData(){return objects.map(o=>({name:o.userData.name,x:o.position.x,y:o.position.y,z:o.position.z,scale:o.scale.x,color:o.userData.color,size:o.userData.size}))}
function saveProject(){localStorage.setItem('WorldCodeProject',JSON.stringify(projectData()));status.textContent='✓ Project saved locally'}
function loadProject(){const raw=localStorage.getItem('WorldCodeProject');if(!raw)return;objects.slice().forEach(o=>scene.remove(o));objects.length=0;JSON.parse(raw).forEach(d=>{const o=addPart(d.name,d.x,d.y,d.z,d.size?.[0]||2,d.size?.[1]||1,d.size?.[2]||2,parseInt(d.color.slice(1),16));o.scale.set(d.scale||1,d.scale||1,d.scale||1)});selected=null;renderTree();showProps();status.textContent='✓ Project loaded'}
document.getElementById('addBtn').onclick=()=>{const o=addPart('Part '+(objects.length),0,1,0);select(o)};document.getElementById('deleteBtn').onclick=()=>{if(selected&&selected.userData.name!=='Baseplate'){scene.remove(selected);objects.splice(objects.indexOf(selected),1);selected=null;showProps();renderTree();status.textContent='Deleted'}};document.getElementById('playBtn').onclick=()=>{running=true;status.textContent='▶ Playing'};document.getElementById('stopBtn').onclick=()=>{running=false;status.textContent='■ Stopped'};document.getElementById('saveBtn')?.addEventListener('click',saveProject);document.getElementById('loadBtn')?.addEventListener('click',loadProject);init();
