const viewport=document.getElementById('viewport');const tree=document.getElementById('tree');const props=document.getElementById('properties');const status=document.querySelector('.status');
let scene,camera,renderer,raycaster,mouse,selected=null,running=false;const objects=[];
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x0d1014);camera=new THREE.PerspectiveCamera(60,1,.1,1000);camera.position.set(7,6,9);camera.lookAt(0,0,0);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));viewport.appendChild(renderer.domElement);raycaster=new THREE.Raycaster();mouse=new THREE.Vector2();scene.add(new THREE.HemisphereLight(0xffffff,0x334455,2));const grid=new THREE.GridHelper(20,20,0x555b66,0x292e36);scene.add(grid);addPart('Baseplate',0,-.5,0,10,1,10);addPart('Part',0,.5,0,2,1,2);window.addEventListener('resize',resize);renderer.domElement.addEventListener('pointerdown',pick);resize();animate();renderTree()}
function addPart(name,x,y,z,sx=2,sy=1,sz=2){const g=new THREE.BoxGeometry(sx,sy,sz);const m=new THREE.MeshStandardMaterial({color:0x4da3ff,roughness:.75});const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.userData={name,position:o.position,size:[sx,sy,sz]};scene.add(o);objects.push(o);return o}
function renderTree(){tree.innerHTML='<div class="node">▾ Workspace</div><div class="node child">▾ World</div>';objects.forEach((o,i)=>{const d=document.createElement('div');d.className='node child'+(o===selected?' selected':'');d.textContent='▣ '+o.userData.name;d.onclick=()=>select(o);tree.appendChild(d)})}
function select(o){selected=o;objects.forEach(x=>x.material.emissive.setHex(0));if(o)o.material.emissive.setHex(0x224466);showProps();renderTree();status.textContent=o?'Selected: '+o.userData.name:'Ready'}
function showProps(){if(!selected){props.innerHTML='<p class="muted">Select an object.</p>';return}const p=selected.position;props.innerHTML=`<div class="prop"><label>Name</label><input id="name" value="${selected.userData.name}"></div><div class="prop"><label>Position X</label><input id="px" type="number" value="${p.x}"></div><div class="prop"><label>Position Y</label><input id="py" type="number" value="${p.y}"></div><div class="prop"><label>Position Z</label><input id="pz" type="number" value="${p.z}"></div>`;['name','px','py','pz'].forEach(id=>document.getElementById(id).addEventListener('change',()=>{if(id==='name')selected.userData.name=document.getElementById(id).value;else selected.position[id[1].toLowerCase()]=Number(document.getElementById(id).value);renderTree()}))}
function pick(e){const r=renderer.domElement.getBoundingClientRect();mouse.x=((e.clientX-r.left)/r.width)*2-1;mouse.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(mouse,camera);const hits=raycaster.intersectObjects(objects);select(hits.length?hits[0].object:null)}
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)}
function animate(){requestAnimationFrame(animate);if(running)objects.filter(o=>o.userData.name!=='Baseplate').forEach(o=>o.rotation.y+=.01);renderer.render(scene,camera)}
document.getElementById('addBtn').onclick=()=>{const o=addPart('Part '+(objects.length),0,1,0);select(o)};document.getElementById('deleteBtn').onclick=()=>{if(selected&&selected.userData.name!=='Baseplate'){scene.remove(selected);objects.splice(objects.indexOf(selected),1);selected=null;showProps();renderTree()}};document.getElementById('playBtn').onclick=()=>{running=true;status.textContent='▶ Playing'};document.getElementById('stopBtn').onclick=()=>{running=false;status.textContent='■ Stopped'};init();
