plugins { id 'com.android.application' }

android {
    namespace 'com.sami.worldcode'
    compileSdk 35

    defaultConfig {
        applicationId 'com.sami.worldcode'
        minSdk 23
        targetSdk 35
        versionCode (project.findProperty('versionCode') ?: '2').toInteger()
        versionName project.findProperty('versionName') ?: '0.0.2'
    }
}
