plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sami.worldcode'
    compileSdk 35

    defaultConfig {
        applicationId 'com.sami.worldcode'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '0.0.2'
    }

    if (project.hasProperty('versionCode')) {
        defaultConfig.versionCode = Integer.parseInt(project.property('versionCode').toString())
    }
    if (project.hasProperty('versionName')) {
        defaultConfig.versionName = project.property('versionName').toString()
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['/META-INF/AL2.0', '/META-INF/LGPL2.1']
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
}
